#model_id: "stabilityai/stable-diffusion-3-medium-diffusers"
model_id: "sd-legacy/stable-diffusion-v1-5"
prompt: "a photo of a cat"
width: 512
height: 512
num_samples: 3
num_inference_step: 50
guidance_scale: 7.0
xformers: false
